import os
import glob
import subprocess
import sys

# Configuration
SOURCE_DIR = "source_emojis"

def main():
    # 1. Ensure the source directory exists
    if not os.path.exists(SOURCE_DIR):
        os.makedirs(SOURCE_DIR)
        print(f"📁 Created folder '{SOURCE_DIR}'.")
        print("Please drop your transparent emoji PNGs into this folder and run the script again!")
        sys.exit(0)

    # 2. Find all PNGs
    png_files = glob.glob(os.path.join(SOURCE_DIR, "*.png"))

    if not png_files:
        print(f"⚠️ No PNG files found in '{SOURCE_DIR}'.")
        sys.exit(0)

    print(f"🚀 Found {len(png_files)} images. Starting batch conversion to .bin files...\n")

    # 3. Process each file
    for filepath in png_files:
        # Extract just the filename (e.g., "skull.png" -> "SKULL")
        basename = os.path.basename(filepath)
        icon_name = os.path.splitext(basename)[0].upper()

        # Clean up names with spaces or dashes
        icon_name = icon_name.replace(" ", "_").replace("-", "_")

        # Call the converter script using subprocess, adding the --bin flag!
        result = subprocess.run(
            [
                sys.executable,
                "image_to_icon.py",
                filepath,
                icon_name,
                "--autocrop",
                "--pad",
                "--bin"
            ],
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            # Print the success message generated by emoji_to_icon.py
            print(result.stdout.strip())
        else:
            print(f"❌ Error converting {basename}:\n{result.stderr}")

    print(f"\n✅ Done! All binary icons are ready in your '{SOURCE_DIR}' folder.")

if __name__ == "__main__":
    main()
